//go:build mage
// +build mage
// Code generated by mage; DO NOT EDIT.

//nolint:all

package main

import (
	"fmt"
	"os"

	"github.com/magefile/mage/mg"
)

// Default target to run when none is specified
var Default = All

// All runs all tasks: InitDB, Migrate, and Seed
func All() {
	mg.Deps(InitDB, Migrate, Seed)
}

// InitDB initializes the SQLite database by creating words.db if it doesn't exist.
func InitDB() error {
	fmt.Println("Initializing database: creating words.db file if not exist...")
	_, err := os.Stat("words.db")
	if os.IsNotExist(err) {
		f, err := os.Create("words.db")
		if err != nil {
			return err
		}
		return f.Close()
	}
	return nil
}

// Migrate runs database migrations found in db/migrations
func Migrate() error {
	fmt.Println("Running migrations...")
	// TODO: Implement migration logic
	return nil
}

// Seed loads seed data from db/seeds folder
func Seed() error {
	fmt.Println("Seeding database...")
	// TODO: Implement seeding logic
	return nil
}
